spring.application.name=webapp
spring.jpa.properties.hibernate.hbm2ddl.auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.open-in-view=false
server.port=8080
server.address=0.0.0.0

# Production database properties
db.url=jdbc:mysql://localhost:3306/say-my-name
db.username=adminsaymyname
db.password=Qw\u20ACrty1234
db.driver=com.mysql.cj.jdbc.Driver

# Propri�t�s de Spring Mail
spring.mail.host=smtp.office365.com
spring.mail.port=587
spring.mail.username=service.mynewro@outlook.com
spring.mail.password=Motdepassedur!
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true